server:
  port: 9999

  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  profiles:
    active:
      - ${PROFILE:develop}

    group:
      green: "server"
      develop: "dev, env"

  redis:
    host: localhost # 서버 host
    port: 6379 # redis 서버 포트

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.soundbridge.domain
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

OPENVIDU_URL: http://localhost:4443/
OPENVIDU_SECRET: MY_SECRET

LOGIN_SUCCESS_URL: http://localhost:5173/login-success?accessToken=

---
spring:
  config:
    activate:
      on-profile: "dev"

server:
  port: 9999

---
spring:
  config:
    activate:
      on-profile: "server"

  datasource:
    url: jdbc:mysql://${DATABASE_URL}/soundbridge?serverTimeZone=Asia/Seoul
    username: ${DATABASE_ID}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${BASE_URL} # 서버 host
    port: 6379 # redis 서버 포트

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: ${KAKAO_CLIENT_ID}
#            redirect-uri: ${KAKAO_REDIRECT_URL}
#            client-authentication-method: POST
#            client-secret: ${KAKAO_CLIENT_SECRET}
#            authorization-grant-type: authorization_code
#            scope:
#              - profile_nickname
#              - account_email
#              - profile_image
#              - gender
#              - age_range
#            client_name: kakao
#          naver:
#            client-id: ${NAVER_CLIENT_ID}
#            redirect-uri: ${NAVER_REDIRECT_URL}
#            client-authentication-method: POST
#            client-secret: ${NAVER_CLIENT_SECRET}
#            authorization-grant-type: authorization_code
#            client_name: naver
#          google:
#            client_id: ${GOOGLE_CLIENT_ID}
#            client_secret: ${GOOGLE_CLIENT_SECRET}
#            redirect_uri: ${GOOGLE_REDIRECT_URL}
#            scope:
#              - email
#              - profile
#              - https://www.googleapis.com/auth/profile.agerange.read
#              - https://www.googleapis.com/auth/user.gender.read
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response

servers:
  url: https://j8a703.p.ssafy.io/
  description: Production server

springdoc:
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.soundbridge.domain
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

LOGIN_SUCCESS_URL: ${LOGIN_SUCCESS_URL}

OPENVIDU_URL: ${OPENVIDU_URL}
OPENVIDU_SECRET: ${OPENVIDU_SECRET}

server:
  port: 9999

jwt:
  token:
    secret-key: ${JWT_TOKEN_SECRET_KEY}
  access-token:
    expire-length: 300000 # 300000 #5분
  refresh-token:
    expire-length: 1209600000 #14일
